// OPEN CARD MODAL CONSTANTS
export const SET_CARD_OPEN_MODAL_TRUE = 'SET_CARD_OPEN_MODAL_TRUE';
export const SET_CARD_OPEN_MODAL_FALSE = 'SET_CARD_OPEN_MODAL_FALSE';
// EDIT CARD MODAL CONSTANTS
export const SET_CARD_EDIT_MODAL_TRUE = 'SET_CARD_EDIT_MODAL_TRUE';
export const SET_CARD_EDIT_MODAL_FALSE = 'SET_CARD_EDIT_MODAL_FALSE';
// ADD CARD MODAL CONSTANTS
export const SET_CARD_ADD_MODAL_TRUE = 'SET_CARD_ADD_MODAL_TRUE';
export const SET_CARD_ADD_MODAL_FALSE = 'SET_CARD_ADD_MODAL_FALSE';
// EDIT BUCKET NAME MODAL
export const SET_EDIT_BUCKET_NAME_MODAL_TRUE =
  'SET_EDIT_BUCKET_NAME_MODAL_TRUE';
export const SET_EDIT_BUCKET_NAME_MODAL_FALSE =
  'SET_EDIT_BUCKET_NAME_MODAL_FALSE';
// DELETE CARD MODAL
export const SET_CARD_DELETE_MODAL_TRUE = 'SET_CARD_DELETE_MODAL_TRUE';
export const SET_CARD_DELETE_MODAL_FALSE = 'SET_CARD_DELETE_MODAL_FALSE';
// SET ALL CARD CONSTANT
export const SET_ALL_CARDS = 'SET_ALL_CARDS';
// SET ALL CARD TYPE CONSTANTS
export const SET_ALL_CARD_TYPES = 'SET_ALL_CARD_TYPES';
// SHOW NOTIFICATION CONSTANT
export const SHOW_NOTIFICATION_MESSAGE = 'SHOW_NOTIFICATION_MESSAGE';
// HIDE NOTIFICATION CONSTANT
export const HIDE_NOTIFICATION_MESSAGE = 'HIDE_NOTIFICATION_MESSAGE';
// ADD BUCKET MODAL
export const SHOW_ADD_BUCKET_MODAL = 'SHOW_ADD_BUCKET_MODAL';
// HIDE BUCKET MODAL
export const HIDE_ADD_BUCKET_MODAL = 'HIDE_ADD_BUCKET_MODAL';
// SET BUCKET VIEW
export const SET_BUCKET_VIEW = 'SET_BUCKET_VIEW';
// SET HISTORY VIEW
export const SET_HISTORY_VIEW = 'SET_HISTORY_VIEW';
// SHOW DELETE BUCKET MODAL
export const SHOW_DELETE_BUCKET_MODAL = ' SHOW_DELETE_BUCKET_MODAL';
// HIDE DELETE BUCKET MODAL
export const HIDE_DELETE_BUCKET_MODAL = 'HIDE_DELETE_BUCKET_MODAL';
